stages:
  - "Code quality, linting, syntax, code style"
  - "Verify package install"

Validations:
  stage: "Code quality, linting, syntax, code style"
  before_script:
    - apt-get clean all && apt-get update
    - apt-get install -y shellcheck curl
  script:
    - shellcheck --format=gcc $(find . -name '*.sh.in' -not -iwholename '*.git*')
    - ./tests/installer/checksums.sh
  variables:
    LOCAL_ONLY: "true"

job 3:
  stage: "Verify package install"
  before_script:
    - curl -s https://packagecloud.io/install/repositories/netdata/netdata-devel/script.deb.sh | sudo bash
  script:
    - apt-get install -y netdata
    - curl -s http://localhost:19999/api/v1/info | grep version || (echo "Service not started" && exit 1)
    - apt-get remove -y netdata
